<?php
/**
 * @file
 * Code for the Dennis Facebook Instant Articles feature.
 */

include_once 'dennis_fb_instant_articles.features.inc';
/**
 * @file
 * Code for the Dennis Facebook Instant Articles module.
 */

require_once __DIR__ . '/vendor/autoload.php';

/**
 * Implements hook_entity_info_alter().
 */
function dennis_fb_instant_articles_entity_info_alter(&$entity_info) {
  $entity_types = fb_instant_articles_display_get_article_entity_types();
  foreach (array_keys($entity_types) as $entity_type) {
    $entity_info[$entity_type]['view modes']['fb_instant_article'] = array(
      'label' => t('Facebook Instant Articles'),
      'custom settings' => FALSE,
    );
  }
}
